### ISSUE TITLE
Help installing

### ISSUE THREAD

**Issue by rafaeln** [y20k/transistorone#2]
Hi. Is the apk available somewhere for download? Or do I need to compile it myself? Thanks for the great app!

**Comment by y20k** [comment]
Hi. The APK is available here.
https://github.com/y20k/transistorone/releases/tag/v3.2.5

(The app is several years old and unmaintained, if possible you should switch to the "new" Transistor app https://codeberg.org/y20k/transistor)

**Comment by rafaeln** [comment]
It's for an old Android 5 phone that is just beginning a new life as a radio tuner / mp3 player. Thanks!
